# Generated by Django 4.0.6 on 2022-09-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
